# Apply after a dataset config with a second --config argument.
model:
  class_path: diffusion.GenerativeModel
  init_args:
    model_type: score
    trajectory: vp
    prediction_type: score
    sampling_scheduler: unipc
    sampling_steps: 30
trainer:
  name: score_vp
